version: "3.9"
services:
  restaurant-booking-system-postgres:
    image: postgres:14.7
    ports:
      - "5432:5432"
    volumes:
      - restaurant-booking-system:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
volumes:
  restaurant-booking-system:
    driver: local
